services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  main:

    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - "USER_ID=${UID:-1000}"
        - "GROUP_ID=${GID:-1000}"

    user: "${UID:-1000}:${GID:-1000}"

    volumes:
      # home fallback
      # - $HOME:/.home:cached

      # ssh & gnupg
      - $HOME/.ssh:/home/rust/.ssh
      # - $HOME/.gnupg:/home/rust/.gnupg

      # project mounting
      - ..:/home/rust/crap-lang

      # zsh
      # - .zshrc:/home/rust/.zshrc
      # - local:/home/rust/.local
      # - cache:/home/rust/.cache

    environment:
      - TZ="Europe/Berlin"

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  local:
    name: "local"
  cache:
    name: "cache"